### ISSUE TITLE
What it is???

### ISSUE THREAD

**Issue by HeaTTheatR** [mcroni/KivyLiteEmulator#1]
Installed it. Launched it. Deleted it.
No one needs this without documentation!

```python
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/plyer/utils.py", line 96, in _ensure_obj
     mod = __import__(module, fromlist='.')
   File "/usr/local/lib/python3.7/site-packages/plyer/platforms/macosx/filechooser.py", line 7, in <module>
     from pyobjus import autoclass, objc_arr, objc_str
 ModuleNotFoundError: No module named 'pyobjus'
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/Users/macbookair/Downloads/KivyLiteEmulator-master/main.py", line 678, in <module>
     KivyEmu().run()
   File "/usr/local/lib/python3.7/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/usr/local/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/usr/local/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python3.7/site-packages/kivy/base.py", line 342, in idle
     self.dispatch_input()
   File "/usr/local/lib/python3.7/site-packages/kivy/base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/local/lib/python3.7/site-packages/kivy/base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/Users/macbookair/Downloads/KivyLiteEmulator-master/kivymd/list.py", line 450, in on_touch_up
     super().on_touch_up(touch)
   File "/Users/macbookair/Downloads/KivyLiteEmulator-master/kivymd/ripplebehavior.py", line 84, in on_touch_up
     return super().on_touch_up(touch)
   File "/usr/local/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "/Users/macbookair/Downloads/KivyLiteEmulator-master/main.py", line 657, in <lambda>
     lambda x: self.choose(),
   File "/Users/macbookair/Downloads/KivyLiteEmulator-master/main.py", line 458, in choose
     filechooser.open_file(on_selection=self.handle_selection)
   File "/usr/local/lib/python3.7/site-packages/plyer/facades/filechooser.py", line 50, in open_file
     return self._file_selection_dialog(mode="open", *args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/plyer/facades/filechooser.py", line 70, in _file_selection_dialog
     raise NotImplementedError()
 NotImplementedError
```

Why use a not cross-platform `FileChooser` if `KivyMD` has an excellent cross-platform dialog for selecting files?

This app does not work even if you specify the path to the file bypassing the above error.

![rrrr](https://user-images.githubusercontent.com/16930280/68175535-9fa1cd00-ff92-11e9-96c0-e9ab5c878a14.gif)

**Comment by mcroni** [comment]
Thanks for reviewing this.I added detailed instructions on how to make it run. If you've found a bug and you're interested in this tool, you follow the right procedures in open source.

**Comment by HeaTTheatR** [comment]
@mcroni Your instructions do not work! I have pointed out obvious mistakes that you prefer to keep quiet about. At least my question should not be closed.
